### ISSUE TITLE
Using Ember.logger is deprecated.

### ISSUE THREAD

**Issue by BillBrower** [201-created/ember-cli-fake-server#105]
Use of `Ember.logger` is deprecated and `Ember.logger` will be removed in Ember 4.0.

https://deprecations-app-prod.herokuapp.com/deprecations/v3.x/#toc_ember-console-deprecate-logger

**Comment by rohitpaulk** [comment]
Note: This was fixed in https://github.com/201-created/ember-cli-fake-server/pull/103

**Comment by rohitpaulk** [comment]
Doesn't look like there's been a release since then though..

**Comment by rohitpaulk** [comment]
@bantic could you help out with a release here?

**Comment by bantic** [comment]
@rohitpaulk Released in v0.6.0! Thanks for the ping

**Comment by rohitpaulk** [comment]
Thanks @bantic!
