### ISSUE TITLE
How can I configure passthrough on Pretender instance?

### ISSUE THREAD

**Issue by taras** [201-created/ember-cli-fake-server#4]
I would like to be able to specify passthrough on the Pretender instance. I don't see any exposed API.

/cc @bantic

**Comment by bantic** [comment]
seems like exposing a passthroughRequest method would be good?

```
import { passthroughRequest } from 'ember-cli-fake-server';

// in test:
passthroughRequest('get', '/api/let-this-through');
```

**Comment by taras** [comment]
Looks like that'll work :)
